version: '3'

services:
  script:
    container_name: keycrm-opencart-sync
    build: .
    restart: unless-stopped
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"